[package]
name = "digenome_seek"
version = "0.1.0"
authors = ["bitsyamagu <dyamaguc@bits.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = "0.38.2"
